# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Donkhouse

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@main
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-test1
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt
    - uses: browser-actions/setup-chrome@latest
    - name: Clear logs directory
      run: rm -rf logs
    - name: Run script
      run: python download_files.py
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: transaction-logs
        path: logs/
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: transaction-logs
    - name: Print files before cleanup
      run: |
        files=(logs/*)
        for file in "${files[@]}"; do
          echo "$file"
        done
    - name: Error check and cleanup log folder
      run: find ./logs \( -type f \! -name "*_ledger.csv" -a \! -name "*_hand_histories.txt" -o -size 0 \) -delete
    - name: Print files after cleanup
      run: |
        files=(logs/*)
        for file in "${files[@]}"; do
          echo "$file"
        done
    - name: Run parse.py for each log file
      run: |
        files=(logs/*)
        for ((i=0; i<${#files[@]}; i+=2)); do
          hand_histories="${files[i]}"
          ledger="${files[i+1]}"
          python parse_downloads.py "$hand_histories" "$ledger" 
        done
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add info.pickle
        git commit -m "update data" -a     
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
